### ISSUE TITLE
Fabric 1.16.2 defaultconfigs error upon startup

### ISSUE THREAD

**Issue by mahjerion** [TheRandomLabs/RandomConfigs#13]
I get an error using the example you provided - same as what I had before. Here's what my .json looks like:
`[
    "source": "options.txt",
    "destination": "options.txt",
    "side": "client",
    "version": 0
]`
and here's the error I get: [pastebin](https://pastebin.com/nbwDitsm)

I tried adding curly braces before and after likeso, as well as nested within the square brackets:
`{[
    "source": "options.txt",
    "destination": "options.txt",
    "side": "client",
    "version": 0
]}`
and I also error: [pastebin](https://pastebin.com/uwxh6rvu)

Appreciate the help so far!

**Comment by TheRandomLabs** [comment]
Tell me what error you get (if any) for this:
`[{ "source": "options.txt", "destination": "options.txt", "side": "client", "version": 0 }]`

**Comment by mahjerion** [comment]
Ahh it worked thanks. The issue I had at first was leaving destination as "" thinking it was meant to be sent to the root folder. Cheers for all the help!

**Comment by budgej** [comment]
> Tell me what error you get (if any) for this:
> `[{ "source": "options.txt", "destination": "options.txt", "side": "client", "version": 0 }]`

I've copied this into my defaultgamerules.json, but options.txt is not being copied from defaultconfigs.  Is there something I can look for in the game log?

Using Fabric for 1.16.4.

**Comment by TheRandomLabs** [comment]
That's the wrong file; you should be copying that into `defaultconfigs.json`. :smile:
