### ISSUE TITLE
Move to Jankson for json interpreting

### ISSUE THREAD

**Issue by LemmaEOF** [TheRandomLabs/RandomConfigs#2]
While json is a good system to use for storing data, a few of its issues (namely the difficulty of bracket-matching and no comments) means it's not that useful for writing config with a lot of the time. However, there's a json processor called [Jankson](https://github.com/falkreon/jankson) that fixes a good few of these issues. It's a drop-in replacement for gson/hjson and works as a preprocessor as well. Would it be possible to switch over to this so config-writing is easier?

**Comment by TheRandomLabs** [comment]
I'll have a look at it. Thanks for the suggestion.

**Comment by TheRandomLabs** [comment]
Sorry for the late reply.
Is what I've done [here](https://github.com/TheRandomLabs/RandomConfigs/commit/f7d62536be3bfdf3900541e613fac3f40601b444) enough, or do I have to do some more integration?

**Comment by LemmaEOF** [comment]
That looks good! It should make it a lot easier for people to use the config system without getting super frustrated.
