### ISSUE TITLE
New attackspeed config sometimes behaves strange. With tools that have non standart attackspeed values.

### ISSUE THREAD

**Issue by SirAron111** [TheRandomLabs/RandomConfigs#5]
I have random tweaks and random config installed I made the configs like the example explained. I am amazed that this actually grabs every tool type even tinkers stuff. But there is a small problem with it. It sometimes randomly displays and uses the normal attack speed of the tool even if it a few seconds before used the changed one and then randomly uses the changed one again (at least for tinkers tools that is especially rapier is buggy).also since there is no clear way to see how attack speed is calculated it is hard to know what to set it to. I set everything to 2 for the test run this made tools with a slower attack speed base get into the -1 or lower stats making them not recharge at all. Is there a way to see how this is calculated? Does it like add 2 or divide the tools base speed by 2 or so? Because the sword ended up with 0.6 from 1.4 that it had before.
Here is what I used for the configs

{
	"attackSpeeds": {
		//Registry name
		"minecraft:iron_sword": {
			//Attack speed (from 0.0 to 1024.0)
			"speed": 3.0,
			//Whether attacks should be disabled during the attack cooldown
			//The attack cooldown will reset when an attack is attempted during the cooldown
			"disableAttacksDuringAttackCooldown": false
		},
		"tconstruct:rapier": {
			"speed": 2.0,
			"disableAttacksDuringAttackCooldown": false
		},
		"tconstruct:mattock": {
			"speed": 2.0,
			"disableAttacksDuringAttackCooldown": false
		},
		"tconstruct:pickaxe": {
			"speed": 2.0,
			"disableAttacksDuringAttackCooldown": false
		},
		"plustic:katana": {
			"speed": 2.0,
			"disableAttacksDuringAttackCooldown": false
		}
	},
	//Overrides RandomTweaks' attack speed configuration option
	"defaultAttackSpeed": 4.0,
	//Overrides RandomTweaks' "misc.disableAttacksDuringAttackCooldown" option
	"disableAttacksDuringAttackCooldownByDefault": false,
	//Whether to enable the /asreload command, which reloads this configuration
	"asreloadCommand": true,
	//Whether to enable the client-sided /asreloadclient command
	"asreloadclientCommand": true,
	//Whether the options in this JSON should take effect (excluding the command toggles)
	"enabled": true
}

**Comment by TheRandomLabs** [comment]
The attack speed controls the length of the cooldown time. The time taken is `1 / attack speed * 20` ticks. Tools have their own attack speed modifiers, which means that depending on the tool being held, the attack speed will differ. By default, the attack speed is 4.0, which means that an empty hand will take a quarter of a second to reach maximum damage. Swords take 2.4 from the attack speed, and axes take between 3 and 3.2 depending on the material. For example, if you set the attack speed for swords to below 2.4, the actual attack speed will be negative.

I'm aware of the visual glitch, but I haven't found a way to fix it yet.

**Comment by TheRandomLabs** [comment]
As far as I can tell, the visual glitch is a vanilla bug.
