### ISSUE TITLE
configs get reset every time

### ISSUE THREAD

**Issue by SirAron111** [TheRandomLabs/RandomConfigs#6]
I managed to find out how I have to set the values now but every time I set the config for the attack speed and get them to work in game they are great but every time the game loads up they get reset to the default ones. They should only get reset when there is no “attackspeeds.json” file in the folder and not once the values inside have been changed replacing it with a default one on every load up.

**Comment by SirAron111** [comment]
here is the config i use https://pastebin.com/Fc81xLnj i just open up the attackspeeds.json in the randomconfigs folder and put exactly this inside it. But it gets reset still did i miss something?

**Comment by TheRandomLabs** [comment]
Crap, I think I made this same error in RandomPortals.
