### ISSUE TITLE
[1.12] WORLD_BORDER_SIZE tag isn't setting the worldborder on a new world

### ISSUE THREAD

**Issue by MasterEnderman** [TheRandomLabs/RandomConfigs#9]
Forge: 14.23.5.2811
RandomConfigs: 1.3.2.3

The Worldborder defaults to 60000000 and the difficulty is not changed

defaultgamerules.json:
```json
{ 
	"commandBlockOutput": { 
		"value": true,
		"forced": true
	},
	"keepInventory": { 
		"value": false,
		"forced": true
	},
	"mobGriefing": { 
		"value": false,
		"forced": true
	},
	"announceAdvancements": { 
		"value": false,
		"forced": true
	},
	"DIFFICULTY": { 
		"value": "hard",
		"forced": true
	},
	"disableNetherPortalCreation": { 
		"value": true,
		"forced": true
	},
	"WORLD_BORDER_SIZE": 20000,
	"MODE_OR_WORLD_TYPE_SPECIFIC": { 
		":flat,void": { 
			"doDaylightCycle": { 
				"value": false,
				"forced": true
			},
			"doWeatherCycle": { 
				"value": false,
				"forced": true
			},
			"doMobSpawning": { 
				"value": false,
				"forced": false
			}
		}
	}
}
```

**Comment by TheRandomLabs** [comment]
I can't reproduce this. If possible, could I have more details?

**Comment by MasterEnderman** [comment]
what kind of details do you want?

is just wrote the file shown above and started up minecraft. the gamerules work fine, but the difficulty isn't set / locked as configured in the json file neither is the worldborder set to the specified value.

**Comment by TheRandomLabs** [comment]
Assuming you were testing this on newly created worlds, could I have a log?

**Comment by MasterEnderman** [comment]
https://gist.github.com/MasterEnderman/df76ded16a3b89f2742ed133253864d9

The world in this log was newly created.

**Comment by TheRandomLabs** [comment]
I couldn't figure this out. If this issue happens again to anyone else, open a new issue.
